### ISSUE TITLE
Error: 403 (Forbidden) from TTS API. Probable cause: Bad token or upstream API changes

### ISSUE THREAD

**Issue by seanhwangwustl** [scottgigante/NaverTTS#3]
Any tips on how to troubleshoot this error? Do I need an API key from Naver?

Error: 403 (Forbidden) from TTS API. Probable cause: Bad token or upstream API changes

**Comment by scottgigante** [comment]
Can you post code to reproduce this error?

**Comment by eric-hansen** [comment]
All you need to do is run the CLI.

```
 eric@DESKTOP-1N3A783  /mnt/c/Users/hanse  navertts-cli --output this.mp3 기복
Error: 403 (Forbidden) from TTS API. Probable cause: Bad token or upstream API changes
```

**Comment by scottgigante** [comment]
That command runs without error for me. Are you running NaverTTS at very high volume?

**Comment by eric-hansen** [comment]
For me no.  It was the first use.

Try it with a fresh install and no pre-defined env vars.  Maybe in a Docker container or something.

**Comment by scottgigante** [comment]
The tests are running just fine in a docker container here: https://github.com/scottgigante/NaverTTS/actions/runs/569278989

Are you on a VPN or some other high-traffic IP address? Can you try from a different IP or computer?

**Comment by scottgigante** [comment]
Just realised -- are you running the latest version from github? Or did you install from pypi?

**Comment by eric-hansen** [comment]
I installed via PyPi

**Comment by scottgigante** [comment]
That explains it -- the pypi version had not been updated since #2 was fixed. Reinstall with `pip install --upgrade navertts` and you should be good.
