### ISSUE TITLE
UserWarning: Gender f not available for language ja

### ISSUE THREAD

**Issue by eniac314** [scottgigante/NaverTTS#7]
I got the warning when using this command:
`navertts-cli --output japanese.mp3 日本語 --lang ja`

I installed navertts-cli version 0.2.0 via pip3 install NaverTTS.

**Comment by scottgigante** [comment]
Thanks for the report! This was actually fixed by #5, but had not been published to PyPi. I've just published `0.3.0`, please install it and feel free to reopen if the issue persists.

**Comment by eniac314** [comment]
I updated to 0.3.0, the issue went away but there is no file being created for the command  `navertts-cli --output japanese.mp3 日本語 --lang ja`, and no error message.  However `navertts-cli --output test.mp3 test --lang en` is working  fine.

**Comment by scottgigante** [comment]
Looks like they changed the name of the speaker. I've updated it in 0.3.1, please try again

**Comment by eniac314** [comment]
All good now!
